import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import 'features/auth/auth_gate_screen.dart';
import 'features/security/vault_security_overlay.dart';
import 'firebase_options.dart';
import 'services/vault_lock_controller.dart';
import 'theme/app_theme.dart';

Future<void> main() async {
  // Firebase must be initialized before any Firebase API is touched,
  // including the auth-state listener AuthGateScreen subscribes to
  // below — so this now runs before runApp().
  WidgetsFlutterBinding.ensureInitialized();

  // Phase 06: sqflite has no native Windows/Linux/macOS implementation,
  // so the FFI-backed desktop factory must be installed before any
  // database is opened. Android continues to use sqflite's default
  // (non-FFI) factory untouched.
  if (Platform.isWindows || Platform.isLinux || Platform.isMacOS) {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  }

  // SETUP REQUIRED: `firebase_options.dart` is generated by running
  // `flutterfire configure` against this project's actual Firebase
  // project (it contains project-specific API keys/app IDs for Android
  // and Windows) — it is not something to hand-write, and is not
  // included here. Run `flutterfire configure` once, selecting Android
  // and Windows, before this will compile.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Phase 13: reads whether a PIN has ever been configured and the
  // saved Auto-Lock Timer preference (both local, via
  // shared_preferences — no dependency on Firebase having resolved
  // yet), and registers the app-lifecycle observer used for auto-lock.
  // Entirely independent of Firebase auth state, per the approved
  // decision — this line has no ordering dependency on the
  // Firebase.initializeApp() call above.
  await VaultLockController.instance.initialize();

  runApp(const ProviderScope(child: FamilyVaultApp()));
}

class FamilyVaultApp extends StatelessWidget {
  const FamilyVaultApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Family Vault',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      // Phase 11: was `const HomeScreen()`. The Dashboard is now reached
      // only after authentication + vault-membership resolution — see
      // AuthGateScreen → VaultGateScreen → HomeScreen(vaultId: ...).
      home: const AuthGateScreen(),
      // Phase 13: wraps the ENTIRE app (every route AuthGateScreen and
      // everything beneath it can navigate to) with the vault-lock
      // overlay — the single insertion point for Phase 13, chosen so
      // no other existing screen needs any change to support locking.
      // See VaultSecurityOverlay's doc comment for the full reasoning.
      builder: (context, child) => VaultSecurityOverlay(child: child!),
    );
  }
}

