import 'dart:convert';

import '../database/database_constants.dart';

/// Persisted Entry — the single row shape saved by the Universal Entry
/// wizard's "Finish" action.
///
/// Pure data + conversion logic (`toMap`/`fromMap`); no database access
/// lives here — that belongs to [DatabaseService], reached only through
/// [EntryRepository]. Dynamic form values are stored as a single
/// JSON-encoded string in [data], since Phase 06 only needs to save and
/// load whole entries (no per-field querying yet).
class Entry {
  const Entry({
    this.id,
    required this.category,
    required this.owner,
    required this.createdAt,
    required this.updatedAt,
    required this.data,
  });

  /// Builds a new (unsaved) [Entry] from the wizard's collected field
  /// values, JSON-encoding [values] and stamping both timestamps as now.
  factory Entry.create({
    required String category,
    required String owner,
    required Map<String, String> values,
  }) {
    final now = DateTime.now().toIso8601String();
    return Entry(
      category: category,
      owner: owner,
      createdAt: now,
      updatedAt: now,
      data: jsonEncode(values),
    );
  }

  /// Reconstructs an [Entry] from a raw SQLite row map.
  factory Entry.fromMap(Map<String, Object?> map) {
    return Entry(
      id: map[DatabaseConstants.columnId] as int?,
      category: map[DatabaseConstants.columnCategory] as String,
      owner: map[DatabaseConstants.columnOwner] as String,
      createdAt: map[DatabaseConstants.columnCreatedAt] as String,
      updatedAt: map[DatabaseConstants.columnUpdatedAt] as String,
      data: map[DatabaseConstants.columnData] as String,
    );
  }

  /// Auto-generated by SQLite on insert; null until the row is saved.
  final int? id;

  final String category;
  final String owner;

  /// Stored as ISO8601 strings — SQLite has no native datetime column.
  final String createdAt;
  final String updatedAt;

  /// JSON-encoded `Map<String, String>` of the dynamic form's field
  /// labels to entered values.
  final String data;

  /// Converts to a row map for `sqflite`'s `insert()`. [id] is omitted
  /// when null so the column's AUTOINCREMENT default applies.
  Map<String, Object?> toMap() {
    return {
      if (id != null) DatabaseConstants.columnId: id,
      DatabaseConstants.columnCategory: category,
      DatabaseConstants.columnOwner: owner,
      DatabaseConstants.columnCreatedAt: createdAt,
      DatabaseConstants.columnUpdatedAt: updatedAt,
      DatabaseConstants.columnData: data,
    };
  }

  /// Returns a copy with the given fields replaced. Used by Phase 07's
  /// Edit flow to produce an updated row (same [id]/[createdAt], new
  /// [data]/[updatedAt]) without reconstructing the whole object by hand.
  Entry copyWith({
    int? id,
    String? category,
    String? owner,
    String? createdAt,
    String? updatedAt,
    String? data,
  }) {
    return Entry(
      id: id ?? this.id,
      category: category ?? this.category,
      owner: owner ?? this.owner,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      data: data ?? this.data,
    );
  }
}
